---
name: Renew iLO SSL Certificates
'on':
  schedule:
    - cron: '0 0 1 * *'
  push:

jobs:
  renew_certs:
    strategy:
      matrix:
        hostname: [ilo.pve01.simn.io, ilo.truenas01.simn.io]
    runs-on: ubuntu-latest
    env:
      ILO_USER: ${{ secrets.ILO_USER }}
      ILO_PASS: ${{ secrets.ILO_PASS }}
      CF_Token: ${{ secrets.CF_Token }}
      CF_Zone_ID: ${{ secrets.CF_Zone_ID }}
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      
      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Install acme.sh
        run: |
          git clone --depth 1 https://github.com/acmesh-official/acme.sh.git
          cd acme.sh && ./acme.sh --force --install -m letsencrypt@simn.io

      - uses: nick-fields/retry@v2
        with:
          max_attempts: 3
          retry_on: error
          timeout_minutes: 60
          command: |
            hpilo_cli -l $ILO_USER -p $ILO_PASS ${{ matrix.hostname }} certificate_signing_request country= state= locality= organization= organizational_unit= common_name=${{ matrix.hostname }} 2>/dev/null

            # Wait for CSR Request to Complete
            sleep 60

            hpilo_cli -l $ILO_USER -p $ILO_PASS ${{ matrix.hostname }} certificate_signing_request country= state= locality= organization= organizational_unit= common_name=${{ matrix.hostname }} > csr_${{ matrix.hostname }}.csr

      - name: Sign Certificate with letsencrypt
        run: bash /home/runner/.acme.sh/acme.sh --signcsr  --csr csr_${{ matrix.hostname }}.csr  --dns  dns_cf --server letsencrypt

      - name: Upload signed certificate to iLO
        run: |
          CERTFILE="/home/runner/.acme.sh/${{ matrix.hostname }}/${{ matrix.hostname }}.cer"
          hpilo_cli -l $ILO_USER -p $ILO_PASS ${{ matrix.hostname }} import_certificate certificate="$(cat $CERTFILE)"
