---
name: Renew iLO SSL Certificates
'on':
  push:

jobs:
  renew-truenas01:
    runs-on: ubuntu-latest
    env:
      ILO_HOSTNAME: "ilo.pve01.simn.io"
      ILO_IP: "192.168.2.200"
      ILO_USER: ${{ secrets.ILO_USER }}
      ILO_PASS: ${{ secrets.ILO_PASS }}
      CF_Token: 
      CF_Zone_ID: 
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      
      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Install acme.sh
        run: |
          git clone https://github.com/acmesh-official/acme.sh.git /install_acme.sh/

          cd /install_acme.sh \
            && ([ -f /install_acme.sh/acme.sh ] \
            && /install_acme.sh/acme.sh --install || curl https://get.acme.sh | sh) \
            && rm -rf /install_acme.sh/

          # echo "$GITHUB_WORKSPACE/.acme.sh/acme.sh" >> $GITHUB_PATH

      # - name: Create Certificate CSR
      #   run: |
      #     hpilo_cli -l $ILO_USER -p $ILO_PASS $ILO_IP certificate_signing_request country= state= locality= organization= organizational_unit= common_name=$ILO_HOSTNAME || true

      #     # Wait for CSR Request to Complete
      #     sleep 60

      #     hpilo_cli -l $ILO_USER -p $ILO_PASS $ILO_IP certificate_signing_request country= state= locality= organization= organizational_unit= common_name=$ILO_HOSTNAME > csr_$ILO_HOSTNAME.csr

      - name: Upload Signed Certificate to iLO
        run: |
          find .
